basePath: /
definitions:
  entities.DeviceType:
    enum:
    - MOBILE
    - COMPUTER
    type: string
    x-enum-varnames:
    - MOBILE
    - COMPUTER
  response.Error:
    properties:
      data:
        example: "null"
        type: string
        x-nullable: true
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  response.Success:
    properties:
      data:
        type: object
      isSuccess:
        type: boolean
      message:
        example: "null"
        type: string
        x-nullable: true
    type: object
  room.CreateCommand:
    properties:
      roomName:
        type: string
      roomPassword:
        type: string
      userId:
        type: string
    required:
    - roomName
    - roomPassword
    - userId
    type: object
  user.CreateCommand:
    properties:
      device:
        $ref: '#/definitions/user.DeviceDTO'
      external_id:
        type: string
      name:
        type: string
      surname:
        type: string
    required:
    - device
    - external_id
    - name
    - surname
    type: object
  user.DeviceDTO:
    properties:
      device_type:
        $ref: '#/definitions/entities.DeviceType'
      fingerprint:
        type: string
      friendly_name:
        type: string
    required:
    - device_type
    - fingerprint
    - friendly_name
    type: object
host: localhost:7865
info:
  contact: {}
  description: This is the API for the RoomPlay service.
  title: RoomPlay API
  version: "1.0"
paths:
  /api/v1/room:
    post:
      consumes:
      - application/json
      description: Creates a new room in the system
      parameters:
      - description: Create Room
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/room.CreateCommand'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Create a new room
      tags:
      - rooms
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: Creates a new user in the system
      parameters:
      - description: Login user
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/user.CreateCommand'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Logins a new user with data from OAuth
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer {token}"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
