basePath: /api/v1
definitions:
  join.RoomCommand:
    properties:
      roomName:
        type: string
      roomPassword:
        type: string
      userId:
        type: string
    required:
    - roomName
    - roomPassword
    - userId
    type: object
  response.Error:
    properties:
      data:
        example: "null"
        type: string
        x-nullable: true
      message:
        type: string
    type: object
  response.Success:
    properties:
      data:
        type: object
      message:
        example: "null"
        type: string
        x-nullable: true
    type: object
host: localhost:7654
info:
  contact: {}
  description: This is the API for the RoomPlay service.
  title: RoomPlay API
  version: "1.0"
paths:
  /api/v1/room:
    post:
      consumes:
      - application/json
      description: Creates a new room in the system
      parameters:
      - description: Join Room
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/join.RoomCommand'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Join a new room
      tags:
      - rooms
  /auth/google/login:
    post:
      consumes:
      - application/json
      description: Starts the OAuth2 flow by generating a state cookie and redirecting
        to Google's authorization endpoint.
      produces:
      - application/json
      responses:
        "302":
          description: Redirect to Google OAuth
          schema:
            type: string
        "403":
          description: Invalid redirect URL
          schema:
            $ref: '#/definitions/response.Error'
      summary: Initiate Google OAuth2 login
      tags:
      - AuthenticationController
  /user/data:
    get:
      consumes:
      - application/json
      description: Get user data based on the provided context
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Retrieve user data
      tags:
      - user
securityDefinitions:
  BearerAuth:
    description: Type "Bearer {token}"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
